from types import SimpleNamespace
import unittest
from unittest import mock

from ppp import ppp


class CheckTagTest(unittest.TestCase):

    @mock.patch.object(ppp, 'get_version', return_value='2.0.0')
    @mock.patch.object(ppp, 'Repo')
    def test_duplicate_tag_raises_without_git_operations(self, repo_cls, _get_version):
        repo = repo_cls.return_value
        repo.tags = [SimpleNamespace(name='2.0.0')]

        with self.assertRaises(ValueError) as error:
            ppp.check_tag()

        self.assertEqual(str(error.exception), 'Tag Already Pushed to Git')
        repo.git.tag.assert_not_called()
        repo.git.push.assert_not_called()

    @mock.patch.object(ppp, 'get_version', return_value='2.0.0')
    @mock.patch.object(ppp, 'Repo')
    def test_new_tag_is_created_and_pushed(self, repo_cls, _get_version):
        repo = repo_cls.return_value
        repo.tags = [SimpleNamespace(name='1.0.0')]

        self.assertTrue(ppp.check_tag())

        repo.git.tag.assert_called_once_with(
            '2.0.0', m='Release automatically generated by pypi-publisher')
        repo.git.push.assert_called_once_with(tags=True)


if __name__ == '__main__':
    unittest.main()
